apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: shim-copy-daemonset
  namespace: openshift-sandboxed-containers-operator
spec:
  selector:
    matchLabels:
      app: shim-copy
  template:
    metadata:
      labels:
        app: shim-copy
    spec:
      serviceAccountName: default
      nodeSelector:
        node-role.kubernetes.io/kata-oc: ""
      containers:
      - name: file-copy-container
        image: quay.io/openshift_sandboxed_containers/kata-shim:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            if [ ! -f /opt/kata/containerd-shim-kata-v2-gpu ]; then
              mkdir -p /opt/kata
              cp /containerd-shim-kata-v2-gpu /opt/kata/containerd-shim-kata-v2-gpu
              chmod 0755 /opt/kata/containerd-shim-kata-v2-gpu
            fi
            sleep infinity
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -f /opt/kata/containerd-shim-kata-v2-gpu"]
        volumeMounts:
        - name: host-volume
          mountPath: /opt
        securityContext:
          privileged: true
      volumes:
      - name: host-volume
        hostPath:
          path: /opt

