apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    pools.operator.machineconfiguration.openshift.io/coco: ""
  name: coco
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - coco
  nodeSelector:
    matchLabels:
      coco: "true"
