apiVersion: confidentialcontainers.org/v1alpha1
kind: KbsConfig
metadata:
  labels:
    app.kubernetes.io/name: kbsconfig
    app.kubernetes.io/instance: kbsconfig-sample
    app.kubernetes.io/part-of: kbs-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kbs-operator
  name: kbsconfig-sample
  namespace: kbs-operator-system
spec:
  kbsConfigMapName: kbs-config-grpc-sample
  kbsAsConfigMapName: as-config-grpc-sample
  kbsRvpsConfigMapName: rvps-config-grpc-sample
  kbsRvpsRefValuesConfigMapName: rvps-reference-values-sample
  kbsAuthSecretName: kbs-auth-public-key
  kbsServiceType: ClusterIP
  #kbsServiceType: NodePort
  #kbsServiceType: LoadBalancer
  #kbsServiceType: ExternalName
  kbsDeploymentType: MicroservicesDeployment
  #kbsHttpsKeySecretName: kbs-https-key
  kbsSecretResources: ["kbsres1"]
