apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-podvm-image-cm
  namespace: openshift-sandboxed-containers-operator
data:
  # PodVM image distro
  PODVM_DISTRO: rhel

  # Image
  AMI_BASE_NAME: "podvm-image"
  AMI_VERSION_MAJ_MIN: "0.0"
  AMI_VOLUME_SIZE: "30"

  # Packer Instance type
  INSTANCE_TYPE: "c4.xlarge"

  # Pod VM sources
  # If changing the source, then ensure the respective payload binaries are available
  # for the new source
  CAA_SRC: "https://github.com/bpradipt/cloud-api-adaptor.git"
  CAA_REF: "OSC-1.6.0"

  # Booleans
  INSTALL_PACKAGES: "no"
  DOWNLOAD_SOURCES: "no"
  CONFIDENTIAL_COMPUTE_ENABLED: "no"
  DISABLE_CLOUD_CONFIG: "true"
  ENABLE_NVIDIA_GPU: "yes"
  UPDATE_PEERPODS_CM: "yes"
  BOOT_FIPS: "no"

  # NVIDIA GPU vars
  NVIDIA_DRIVER_VERSION: "535"
  NVIDIA_USERSPACE_VERSION: "1.13.5-1"
