# Service to expose the KBS.
apiVersion: v1
kind: Service
metadata:
  name: kbs-np
  namespace: coco-kbs
spec:
  type: NodePort
  selector:
    app: kbs
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
